# SET(CMAKE_PREFIX_PAHT /usr)

# FIND_LIBRARY(PTHREAD_LIB NAMES pthread PATH /usr/lib64)

# IF (NOT PTHREAD_LIB)
	FIND_LIBRARY(PTHREAD_LIB NAMES pthread PATH /usr/lib)
# ENDIF (NOT PTHREAD_LIB)

# IF (PTHREAD_LIB)
# 	SET(PTHREAD_FOUND TRUE)
# ENDIF (PTHREAD_LIB)

FIND_PACKAGE(Threads REQUIRED)